apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Operators
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: operators
    repoURL: 'https://github.com/rmallam/OpenShift-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true