{{- if eq .Values.hostedclusterocpvirt.enabled true }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hostedclusterocpvirt
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: ocpvirthostedcluster
    repoURL: 'https://github.com/rmallam/OpenShift-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}