{{- range .Values.hosted.clusters }}
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: {{ .name }}
  namespace: 'clusters'
  labels:
    "cluster.open-cluster-management.io/clusterset": '{{ .clusterset }}'
spec:
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.29-multi
  pullSecret:
    name: pullsecret-cluster-{{ .name }}
  sshKey:
    name: sshkey-cluster-{{ .name }}
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
    networkType: OVNKubernetes
#  controllerAvailabilityPolicy: HighlyAvailable
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
  infraID: {{ .name }}
  services:
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer 
{{- end }}