{{- range .Values.hosted.clusters }}
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: '{{ .name }}'
  namespace: '{{ .name }}'
spec:
  clusterName: '{{ .name }}'
  clusterNamespace: '{{ .name }}'
  clusterLabels:
    cloud: BareMetal
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
{{- end }}