{{- range .Values.hosted.clusters }}
---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: {{ .nodepool.name }}
  namespace: 'clusters'
spec:
  arch: amd64
  clusterName: {{ .name }}
  replicas: 3
  management:
    autoRepair: false
    upgradeType: Replace
  platform:
    type: KubeVirt
    kubevirt:
      compute:
{{- toYaml .nodepool.compute | nindent 8  }} 
      rootVolume:
        type: Persistent
        persistent:
          size: 32Gi
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.29-multi
{{- end }}