channel: stable-4.12
version: 4.12.35
subscriptions:
  - name: kiali-ossm
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: servicemeshoperator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  - name: serverless-operator
    namespace: openshift-serverless
    channel: stable
    source: redhat-operators
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.10
    source: redhat-operators
  - name: kubevirt-hyperconverged
    namespace: openshift-cnv
    channel: stable
    source: redhat-operators
  - name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    channel: stable
    source: redhat-operators
acm:  ## Deploy multiclusterhub CRD 
  enabled: false
acs:
  enabled: false
sealedsecrets:
  enabled: false ## learn here
gitops:
  enabled: false
knative:
  enabled: false
kafka:
  enabled: false
  dedicatedNode: false
manageclustersonargo:  ## Add the hosted/managed clusters to argocd. clusterset defined for now is managed
   enabled: false
hyperconverged:  ## Deploy openshift virt 
   enabled: true
managedclusterset:
    enable: true
hostedclusterocpvirt:
   enabled: false
